In [2]:
import geopandas as gpd
import matplotlib.pyplot as plt

In [3]:
rsp = gpd.read_file("rsp-data/rsp-3.geojson")

In [4]:
rsp.head()

,fid,Tag,Date,Time,Temp (C),Baro (mb),Depth (m),pH,ORP (REDOX),DO (% Sat),...,_variety,_variance,HISTO_crops,HISTO_water,HISTO_mangrove,HISTO_forest,HISTO_grassland,HISTO_settlements,HISTO_bare_land,geometry
0,1,1,6/10/2019,9:51:00,28.3,1014,0.059999999,7.32,9.5,494.6,...,5.0,3.757342,679,839,606,0,0,557,123,"MULTIPOLYGON (((177.68357 -17.54319, 177.68357..."
1,2,2,6/10/2019,9:52:00,28.4,1014,0.189999998,7.2,17.1,494.7,...,5.0,3.835843,657,825,604,0,0,585,126,"MULTIPOLYGON (((177.68366 -17.54332, 177.68366..."
2,3,3,6/10/2019,9:52:00,28.4,1014,0.090000004,7.2,20.5,494.7,...,5.0,3.895659,634,821,599,0,0,616,126,"MULTIPOLYGON (((177.68372 -17.54342, 177.68372..."
3,4,4,6/10/2019,9:52:00,28.48,1014,0.159999996,7.21,22.6,494.9,...,5.0,3.916712,625,815,600,0,0,630,125,"MULTIPOLYGON (((177.68372 -17.54349, 177.68372..."
4,5,5,6/10/2019,9:53:00,28.5,1014,0.120000005,7.22,26.5,494.9,...,5.0,3.940420,615,817,597,0,0,653,122,"MULTIPOLYGON (((177.68372 -17.54365, 177.68372..."

In [5]:
rsp.columns

Index(['fid', 'Tag', 'Date', 'Time', 'Temp (C)', 'Baro (mb)', 'Depth (m)',
       'pH', 'ORP (REDOX)', 'DO (% Sat)', 'DO (mg/L)', 'EC (uS/cm @25C)',
       'RES (Ohms.cm)', 'TDS (mg/L)', 'SAL (PSU)', 'SSG (st)',
       'Turbidity (NTU)', 'Nitrate (mg/L)', 'Lat', 'Lon', 'Alt (m)',
       'r2r distance', 'Distance from FSC', 'Lat_DD', 'Lon_DD', 'Lat_filled',
       'Lon_filled', '_count', '_sum', '_mean', '_median', '_stdev', '_min',
       '_max', '_range', '_minority', '_majority', '_variety', '_variance',
       'HISTO_crops', 'HISTO_water', 'HISTO_mangrove', 'HISTO_forest',
       'HISTO_grassland', 'HISTO_settlements', 'HISTO_bare_land', 'geometry'],
      dtype='object')

In [6]:
rsp

,fid,Tag,Date,Time,Temp (C),Baro (mb),Depth (m),pH,ORP (REDOX),DO (% Sat),...,_variety,_variance,HISTO_crops,HISTO_water,HISTO_mangrove,HISTO_forest,HISTO_grassland,HISTO_settlements,HISTO_bare_land,geometry
0,1,1,6/10/2019,9:51:00,28.3,1014,0.059999999,7.32,9.5,494.6,...,5.0,3.757342,679,839,606,0,0,557,123,"MULTIPOLYGON (((177.68357 -17.54319, 177.68357..."
1,2,2,6/10/2019,9:52:00,28.4,1014,0.189999998,7.2,17.1,494.7,...,5.0,3.835843,657,825,604,0,0,585,126,"MULTIPOLYGON (((177.68366 -17.54332, 177.68366..."
2,3,3,6/10/2019,9:52:00,28.4,1014,0.090000004,7.2,20.5,494.7,...,5.0,3.895659,634,821,599,0,0,616,126,"MULTIPOLYGON (((177.68372 -17.54342, 177.68372..."
3,4,4,6/10/2019,9:52:00,28.48,1014,0.159999996,7.21,22.6,494.9,...,5.0,3.916712,625,815,600,0,0,630,125,"MULTIPOLYGON (((177.68372 -17.54349, 177.68372..."
4,5,5,6/10/2019,9:53:00,28.5,1014,0.120000005,7.22,26.5,494.9,...,5.0,3.940420,615,817,597,0,0,653,122,"MULTIPOLYGON (((177.68372 -17.54365, 177.68372..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,307,13/10/2019,11:56:00,28.1,1005,0.219999999,7.74,75.7,498.5,...,5.0,1.571231,0,322,2,847,1331,0,295,"MULTIPOLYGON (((177.8335 -17.69479, 177.8335 -..."
307,308,308,13/10/2019,12:37:00,28.8,1005,0.370000005,7.67,61,499.3,...,5.0,0.979652,0,159,0,144,2211,6,294,"MULTIPOLYGON (((177.8328 -17.68153, 177.8328 -..."
308,309,309,13/10/2019,12:37:00,28.5,1005,0.230000004,7.7,65.3,499,...,5.0,0.973593,0,157,0,145,2209,6,293,"MULTIPOLYGON (((177.83284 -17.68155, 177.83284..."
309,310,310,13/10/2019,17:55:00,29.45,1006,0.350000024,7.62,51.5,500.2,...,6.0,1.221123,0,234,1,1537,789,24,220,"MULTIPOLYGON (((177.81232 -17.6662, 177.81232 ..."
310,311,311,13/10/2019,17:56:00,29.3,1006,0.120000005,7.68,57,499.9,...,6.0,1.220253,0,234,1,1540,788,24,220,"MULTIPOLYGON (((177.81231 -17.66622, 177.81231..."